### PR TITLE
simple medium article style

### PR DESCRIPTION
**Pull request by Real-FEELS**

### CODE REVIEW

**Comment by Real-FEELS** [comment]
and footer updates added.

**Comment by Real-FEELS** [comment]
This is a quote style test Ignore 

> Bacon ipsum dolor amet bacon strip steak burgdoggen sirloin. Pancetta capicola venison, flank chuck buffalo bacon sausage frankfurter. Turkey kevin meatball, t-bone chislic ham pork belly pancetta pork picanha pastrami. Pork belly chicken sausage, leberkas ham hock flank beef chislic. Biltong short loin andouille t-bone. Turducken kielbasa drumstick picanha brisket chicken doner. Shank drumstick chuck, landjaeger sirloin chislic meatloaf.
> 
> Bacon ipsum dolor amet bacon strip steak burgdoggen sirloin. Pancetta capicola venison, flank chuck buffalo bacon sausage frankfurter. Turkey kevin meatball, t-bone chislic ham pork belly pancetta pork picanha pastrami. Pork belly chicken sausage, leberkas ham hock flank beef chislic. Biltong short loin andouille t-bone. Turducken kielbasa drumstick picanha brisket chicken doner. Shank drumstick chuck, landjaeger sirloin chislic meatloaf.

**Comment by FreeTrade** [comment]
Merged, but did I miss something? Not seeing anything related to the article class

**Comment by Real-FEELS** [comment]
Check it out. https://freetrade.github.io/memberdev/?2fad#article?post=2fad197c60

**Comment by FreeTrade** [comment]
Ah I see, okay you're working on the styles within the article. I'm more thinking of the overall look of the page, like having a large type headline and removing the header and footer of the site to make it similar to a very minimalist medium/read type article - think the old one comes closer for that, consider , https://member.cash/?2fad#article?post=2fad197c60

**Comment by Real-FEELS** [comment]
will take a look

**Pull request merged**
